# Generated by Django 5.1.5 on 2025-01-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='directorio',
            field=models.CharField(default='imagenes/predeterminadas', max_length=50),
            preserve_default=False,
        ),
    ]
