# Generated by Django 5.1.5 on 2025-01-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.FileField(upload_to='json/')),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '¨files',
                'ordering': ['-created_at'],
            },
        ),
    ]
