# Generated by Django 5.1.5 on 2025-01-26 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='imagen',
            table='imagenes',
        ),
    ]
